set script_dir [file dirname [file normalize [info script]]]

set ::env(DESIGN_NAME) user_project_wrapper
set ::env(FP_PIN_ORDER_CFG) $script_dir/pin_order.cfg

set ::env(VERILOG_FILES) "$script_dir/../../src/user_project_wrapper.v"
set ::env(VERILOG_FILES_BLACKBOX) "$script_dir/../../src/opentdc_wb_bb.v"

set ::env(CLOCK_PORT) "wb_clk_i"
set ::env(CLOCK_NET) "wb_clk_i"

set ::env(CLOCK_PERIOD) "10"

set ::env(FP_PDN_CORE_RING) 1
set ::env(PDN_CFG) $script_dir/pdn.tcl
set ::env(FP_SIZING) absolute
set ::env(DIE_AREA) "0 0 2920 3520"
set ::env(PL_TARGET_DENSITY) 0.005

set ::env(PL_OPENPHYSYN_OPTIMIZATIONS) 0
set ::env(DIODE_INSERTION_STRATEGY) 0

set macros [list]
#set macros [list "tapline_200_x2_hd" "tapline_200_x2_hd_ref" "delayline_8_hd"]
#set macros [list "delayline_9_hd" "delayline_9_hs"]
# The list of macros is generated by the Makefile
source "$script_dir/macros.tcl"
set macros_lef ""
set macros_gds ""
foreach m $macros {
    set macros_lef "$macros_lef $script_dir/../../lef/$m.lef"
    set macros_gds "$macros_gds $script_dir/../../gds/$m.gds"
}
set ::env(EXTRA_LEFS)      "$macros_lef"
set ::env(EXTRA_GDS_FILES) "$macros_gds"
set ::env(MACRO_PLACEMENT_CFG) $script_dir/macro_placement.cfg

