# SPDX-FileCopyrightText: (c) 2020 Tristan Gingold <tgingold@free.fr>
# SPDX-License-Identifier: Apache-2.0

set script_dir [file dirname [file normalize [info script]]]

set ::env(DESIGN_NAME) user_project_wrapper
set ::env(FP_PIN_ORDER_CFG) $script_dir/pin_order.cfg

set ::env(VERILOG_FILES) "$script_dir/../../src/user_project_wrapper.v"
set ::env(VERILOG_FILES_BLACKBOX) "$script_dir/../../src/user_project_wrapper_bb.v"

set ::env(CLOCK_PORT) "wb_clk_i"
set ::env(CLOCK_NET) "wb_clk_i"

set ::env(CLOCK_PERIOD) "10"

# From caravel

set ::env(PDN_CFG) $script_dir/pdn.tcl
set ::env(FP_PDN_CORE_RING) 1
set ::env(FP_SIZING) absolute
set ::env(DIE_AREA) "0 0 2920 3520"

set ::unit 2.4
set ::env(FP_IO_VEXTEND) [expr 2*$::unit]
set ::env(FP_IO_HEXTEND) [expr 2*$::unit]
set ::env(FP_IO_VLENGTH) $::unit
set ::env(FP_IO_HLENGTH) $::unit

set ::env(FP_IO_VTHICKNESS_MULT) 4
set ::env(FP_IO_HTHICKNESS_MULT) 4

# Need to fix a FastRoute bug for this to work, but it's good
# for a sense of "isolation"
set ::env(MAGIC_ZEROIZE_ORIGIN) 0
set ::env(MAGIC_WRITE_FULL_LEF) 1

set ::env(PL_TARGET_DENSITY) 0.005

set ::env(PL_OPENPHYSYN_OPTIMIZATIONS) 0
set ::env(DIODE_INSERTION_STRATEGY) 0

set macros [list]
#set macros [list "tapline_200_x2_hd" "tapline_200_x2_hd_ref" "delayline_8_hd"]
#set macros [list "delayline_9_hd" "delayline_9_hs"]
# The list of macros is generated by the Makefile
source "$script_dir/macros.tcl"
set macros_lef ""
set macros_gds ""
foreach m $macros {
    set macros_lef "$macros_lef $script_dir/../../lef/$m.lef"
    set macros_gds "$macros_gds $script_dir/../../gds/$m.gds"
}
set ::env(EXTRA_LEFS)      "$macros_lef"
set ::env(EXTRA_GDS_FILES) "$macros_gds"
set ::env(MACRO_PLACEMENT_CFG) $script_dir/macro_placement.cfg

# Obstruction over wb_extender 2, 3, 4
set ::env(GLB_RT_OBS) "met4 108.0 1614.0 1285.63 136.0, met4 108 2514 1285.63 136, met4 1588 2514 1285.63 136"
