/* Generated by Yosys 0.9+2406 (git sha1 f7fdd99, gcc 4.8.5 -fPIC -Os) */

module opentdc(dat_i, clk_i, rst_n_i, bus_i, rst_time_n_i, inp_i, dat_o, ack_o);
  wire _00_;
  wire [7:0] _01_;
  wire _02_;
  wire [7:0] _03_;
  wire _04_;
  wire [7:0] _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire [1:0] _10_;
  wire _11_;
  wire [7:0] _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire [1:0] _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire [7:0] _21_;
  wire _22_;
  wire [7:0] _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire [1:0] _27_;
  wire [7:0] _28_;
  wire _29_;
  wire [7:0] _30_;
  wire [7:0] _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire [1:0] _35_;
  reg [7:0] _36_;
  reg _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire [6:0] _57_;
  wire _58_;
  wire [7:0] _59_;
  wire _60_;
  wire _61_;
  wire [7:0] _62_;
  wire _63_;
  wire _64_;
  wire [7:0] _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  output ack_o;
  reg b_idle;
  reg [1:0] \b_wb.wb_state ;
  input [1:0] bus_i;
  input clk_i;
  input [7:0] dat_i;
  output [7:0] dat_o;
  input inp_i;
  input rst_n_i;
  input rst_time_n_i;
  wire [31:0] tdc0_coarse;
  wire [15:0] tdc0_fine;
  reg tdc0_restart;
  wire tdc0_trigger;
  reg wb_ack;
  reg [7:0] wb_adr;
  reg wb_cyc;
  reg [7:0] wb_dati;
  reg [7:0] wb_dato;
  reg wb_stb;
  reg wb_we;
  always @(posedge clk_i)
      _36_ <= _28_;
  always @(posedge clk_i)
      _37_ <= _29_;
  always @(posedge clk_i)
      wb_dati <= _30_;
  always @(posedge clk_i)
      wb_stb <= _32_;
  always @(posedge clk_i)
      wb_cyc <= _33_;
  always @(posedge clk_i)
      wb_we <= _34_;
  always @(posedge clk_i)
      \b_wb.wb_state  <= _35_;
  assign _38_ = bus_i == 2'h1;
  assign _39_ = ~ rst_n_i;
  assign _40_ = wb_stb & wb_cyc;
  assign _41_ = wb_adr == 8'h00;
  assign _42_ = wb_adr == 8'h01;
  assign _43_ = wb_adr == 8'h02;
  assign _44_ = wb_adr == 8'h03;
  assign _46_ = wb_adr == 8'h04;
  assign _47_ = wb_we ? wb_dati[0] : 1'h0;
  assign _45_ = bus_i == 2'h2;
  assign _48_ = wb_adr == 8'h05;
  assign _49_ = wb_adr == 8'h08;
  assign _50_ = wb_adr == 8'h09;
  assign _51_ = wb_adr == 8'h0a;
  assign _52_ = wb_adr == 8'h0b;
  assign _53_ = wb_adr == 8'h0c;
  assign _54_ = wb_adr == 8'h0d;
  assign _56_ = bus_i == 2'h3;
  assign _67_ = _45_ | _56_;
  function [0:0] \161 ;
    input [0:0] a;
    input [11:0] b;
    input [11:0] s;
    (* parallel_case *)
    casez (s)
      12'b???????????1:
        \161  = b[0:0];
      12'b??????????1?:
        \161  = b[1:1];
      12'b?????????1??:
        \161  = b[2:2];
      12'b????????1???:
        \161  = b[3:3];
      12'b???????1????:
        \161  = b[4:4];
      12'b??????1?????:
        \161  = b[5:5];
      12'b?????1??????:
        \161  = b[6:6];
      12'b????1???????:
        \161  = b[7:7];
      12'b???1????????:
        \161  = b[8:8];
      12'b??1?????????:
        \161  = b[9:9];
      12'b?1??????????:
        \161  = b[10:10];
      12'b1???????????:
        \161  = b[11:11];
      default:
        \161  = a;
    endcase
  endfunction
  assign _55_ = \161 (1'h0, { tdc0_fine[0], tdc0_fine[8], tdc0_coarse[0], tdc0_coarse[8], tdc0_coarse[16], tdc0_coarse[24], 1'h0, tdc0_trigger, 4'h0 }, { _54_, _53_, _52_, _51_, _50_, _49_, _48_, _46_, _44_, _43_, _42_, _41_ });
  function [6:0] \173 ;
    input [6:0] a;
    input [83:0] b;
    input [11:0] s;
    (* parallel_case *)
    casez (s)
      12'b???????????1:
        \173  = b[6:0];
      12'b??????????1?:
        \173  = b[13:7];
      12'b?????????1??:
        \173  = b[20:14];
      12'b????????1???:
        \173  = b[27:21];
      12'b???????1????:
        \173  = b[34:28];
      12'b??????1?????:
        \173  = b[41:35];
      12'b?????1??????:
        \173  = b[48:42];
      12'b????1???????:
        \173  = b[55:49];
      12'b???1????????:
        \173  = b[62:56];
      12'b??1?????????:
        \173  = b[69:63];
      12'b?1??????????:
        \173  = b[76:70];
      12'b1???????????:
        \173  = b[83:77];
      default:
        \173  = a;
    endcase
  endfunction
  assign _57_ = \173 (7'h00, { tdc0_fine[7:1], tdc0_fine[15:9], tdc0_coarse[7:1], tdc0_coarse[15:9], tdc0_coarse[23:17], tdc0_coarse[31:25], 42'h0000038f254 }, { _54_, _53_, _52_, _51_, _50_, _49_, _48_, _46_, _44_, _43_, _42_, _41_ });
  function [0:0] \177 ;
    input [0:0] a;
    input [11:0] b;
    input [11:0] s;
    (* parallel_case *)
    casez (s)
      12'b???????????1:
        \177  = b[0:0];
      12'b??????????1?:
        \177  = b[1:1];
      12'b?????????1??:
        \177  = b[2:2];
      12'b????????1???:
        \177  = b[3:3];
      12'b???????1????:
        \177  = b[4:4];
      12'b??????1?????:
        \177  = b[5:5];
      12'b?????1??????:
        \177  = b[6:6];
      12'b????1???????:
        \177  = b[7:7];
      12'b???1????????:
        \177  = b[8:8];
      12'b??1?????????:
        \177  = b[9:9];
      12'b?1??????????:
        \177  = b[10:10];
      12'b1???????????:
        \177  = b[11:11];
      default:
        \177  = a;
    endcase
  endfunction
  assign _58_ = \177 (1'h0, { 6'h00, _47_, 5'h00 }, { _54_, _53_, _52_, _51_, _50_, _49_, _48_, _46_, _44_, _43_, _42_, _41_ });
  assign _59_ = _40_ ? { _57_, _55_ } : wb_dato;
  assign _60_ = _40_ ? 1'h1 : wb_ack;
  assign _61_ = _40_ ? _58_ : 1'h0;
  assign _62_ = wb_ack ? wb_dato : _59_;
  assign _63_ = wb_ack ? 1'h0 : _60_;
  assign _64_ = wb_ack ? 1'h0 : _61_;
  assign _65_ = _39_ ? wb_dato : _62_;
  assign _66_ = _39_ ? 1'h0 : _63_;
  assign _68_ = _39_ ? 1'h0 : _64_;
  always @(posedge clk_i)
      wb_dato <= _65_;
  always @(posedge clk_i)
      wb_ack <= _66_;
  always @(posedge clk_i)
      tdc0_restart <= _68_;
  function [0:0] \21 ;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \21  = b[0:0];
      3'b?1?:
        \21  = b[1:1];
      3'b1??:
        \21  = b[2:2];
      default:
        \21  = a;
    endcase
  endfunction
  assign _69_ = \21 (b_idle, 3'h1, { _67_, _38_, _09_ });
  function [7:0] \22 ;
    input [7:0] a;
    input [23:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \22  = b[7:0];
      3'b?1?:
        \22  = b[15:8];
      3'b1??:
        \22  = b[23:16];
      default:
        \22  = a;
    endcase
  endfunction
  assign _01_ = \22 (wb_adr, { wb_adr, _31_, wb_adr }, { _67_, _38_, _09_ });
  assign _02_ = _00_ ? 1'h1 : _69_;
  assign _03_ = _00_ ? 8'h00 : _01_;
  always @(posedge clk_i)
      b_idle <= _02_;
  always @(posedge clk_i)
      wb_adr <= _03_;
  assign _04_ = ~ rst_n_i;
  assign _05_ = bus_i[1] ? dat_i : wb_dati;
  assign _06_ = bus_i[1] ? 1'h1 : wb_stb;
  assign _07_ = bus_i[1] ? 1'h1 : wb_cyc;
  assign _08_ = bus_i[1] ? bus_i[0] : wb_we;
  assign _10_ = bus_i[1] ? 2'h1 : \b_wb.wb_state ;
  assign _11_ = \b_wb.wb_state  == 2'h0;
  assign _12_ = wb_ack ? wb_dato : _36_;
  assign _00_ = ~ rst_n_i;
  assign _13_ = wb_ack ? 1'h1 : _37_;
  assign _14_ = wb_ack ? 1'h0 : wb_stb;
  assign _15_ = wb_ack ? 1'h0 : wb_cyc;
  assign _16_ = wb_ack ? 2'h2 : \b_wb.wb_state ;
  assign _17_ = \b_wb.wb_state  == 2'h1;
  assign _18_ = \b_wb.wb_state  == 2'h2;
  assign _19_ = \b_wb.wb_state  == 2'h3;
  function [7:0] \65 ;
    input [7:0] a;
    input [31:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \65  = b[7:0];
      4'b??1?:
        \65  = b[15:8];
      4'b?1??:
        \65  = b[23:16];
      4'b1???:
        \65  = b[31:24];
      default:
        \65  = a;
    endcase
  endfunction
  assign _21_ = \65 (8'hxx, { _36_, _36_, _12_, _36_ }, { _19_, _18_, _17_, _11_ });
  function [0:0] \68 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \68  = b[0:0];
      4'b??1?:
        \68  = b[1:1];
      4'b?1??:
        \68  = b[2:2];
      4'b1???:
        \68  = b[3:3];
      default:
        \68  = a;
    endcase
  endfunction
  assign _22_ = \68 (1'hx, { 1'h0, _37_, _13_, _37_ }, { _19_, _18_, _17_, _11_ });
  assign _09_ = bus_i == 2'h0;
  function [7:0] \70 ;
    input [7:0] a;
    input [31:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \70  = b[7:0];
      4'b??1?:
        \70  = b[15:8];
      4'b?1??:
        \70  = b[23:16];
      4'b1???:
        \70  = b[31:24];
      default:
        \70  = a;
    endcase
  endfunction
  assign _23_ = \70 (8'hxx, { wb_dati, wb_dati, wb_dati, _05_ }, { _19_, _18_, _17_, _11_ });
  function [0:0] \72 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \72  = b[0:0];
      4'b??1?:
        \72  = b[1:1];
      4'b?1??:
        \72  = b[2:2];
      4'b1???:
        \72  = b[3:3];
      default:
        \72  = a;
    endcase
  endfunction
  assign _24_ = \72 (1'hx, { wb_stb, wb_stb, _14_, _06_ }, { _19_, _18_, _17_, _11_ });
  function [0:0] \74 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \74  = b[0:0];
      4'b??1?:
        \74  = b[1:1];
      4'b?1??:
        \74  = b[2:2];
      4'b1???:
        \74  = b[3:3];
      default:
        \74  = a;
    endcase
  endfunction
  assign _25_ = \74 (1'hx, { wb_cyc, wb_cyc, _15_, _07_ }, { _19_, _18_, _17_, _11_ });
  function [0:0] \76 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \76  = b[0:0];
      4'b??1?:
        \76  = b[1:1];
      4'b?1??:
        \76  = b[2:2];
      4'b1???:
        \76  = b[3:3];
      default:
        \76  = a;
    endcase
  endfunction
  assign _26_ = \76 (1'hx, { wb_we, wb_we, wb_we, _08_ }, { _19_, _18_, _17_, _11_ });
  assign _20_ = ~ b_idle;
  function [1:0] \80 ;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \80  = b[1:0];
      4'b??1?:
        \80  = b[3:2];
      4'b?1??:
        \80  = b[5:4];
      4'b1???:
        \80  = b[7:6];
      default:
        \80  = a;
    endcase
  endfunction
  assign _27_ = \80 (2'hx, { 4'h3, _16_, _10_ }, { _19_, _18_, _17_, _11_ });
  assign _28_ = _04_ ? 8'h00 : _21_;
  assign _29_ = _04_ ? 1'h0 : _22_;
  assign _30_ = _04_ ? wb_dati : _23_;
  assign _32_ = _04_ ? 1'h0 : _24_;
  assign _33_ = _04_ ? 1'h0 : _25_;
  assign _31_ = _20_ ? dat_i : wb_adr;
  assign _34_ = _04_ ? wb_we : _26_;
  assign _35_ = _04_ ? 2'h0 : _27_;
  opentdc_core_128 i_tdc0 (
    .clk_i(clk_i),
    .coarse_o(tdc0_coarse),
    .fine_o(tdc0_fine),
    .inp_i(inp_i),
    .restart_i(tdc0_restart),
    .rst_n_i(rst_n_i),
    .rst_time_n_i(rst_time_n_i),
    .trigger_o(tdc0_trigger)
  );
  assign dat_o = _36_;
  assign ack_o = _37_;
endmodule

module opentdc_core_128(clk_i, rst_n_i, rst_time_n_i, restart_i, inp_i, trigger_o, coarse_o, fine_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire [31:0] _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire [30:0] _133_;
  wire [31:0] _134_;
  wire [30:0] _135_;
  wire [31:0] _136_;
  wire _137_;
  wire [30:0] _138_;
  wire [30:0] _139_;
  wire [31:0] _140_;
  wire _141_;
  wire _142_;
  wire [30:0] _143_;
  wire [31:0] _144_;
  wire _145_;
  wire [30:0] _146_;
  wire [30:0] _147_;
  wire [30:0] _148_;
  wire [31:0] _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire [30:0] _153_;
  wire [31:0] _154_;
  wire _155_;
  wire [30:0] _156_;
  wire [30:0] _157_;
  wire [31:0] _158_;
  wire _159_;
  wire _160_;
  wire [30:0] _161_;
  wire [31:0] _162_;
  wire _163_;
  wire [30:0] _164_;
  wire [30:0] _165_;
  wire [30:0] _166_;
  wire [30:0] _167_;
  wire [31:0] _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire [30:0] _173_;
  wire [31:0] _174_;
  wire _175_;
  wire [30:0] _176_;
  wire [30:0] _177_;
  wire [31:0] _178_;
  wire _179_;
  wire _180_;
  wire [30:0] _181_;
  wire [31:0] _182_;
  wire _183_;
  wire [30:0] _184_;
  wire [30:0] _185_;
  wire [30:0] _186_;
  wire [31:0] _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire [30:0] _191_;
  wire [31:0] _192_;
  wire _193_;
  wire [30:0] _194_;
  wire [30:0] _195_;
  wire [31:0] _196_;
  wire _197_;
  wire _198_;
  wire [30:0] _199_;
  wire [31:0] _200_;
  wire _201_;
  wire [30:0] _202_;
  wire [30:0] _203_;
  wire [30:0] _204_;
  wire [30:0] _205_;
  wire [30:0] _206_;
  wire [31:0] _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire [30:0] _213_;
  wire [31:0] _214_;
  wire _215_;
  wire [30:0] _216_;
  wire [30:0] _217_;
  wire [31:0] _218_;
  wire _219_;
  wire _220_;
  wire [30:0] _221_;
  wire [31:0] _222_;
  wire _223_;
  wire [30:0] _224_;
  wire [30:0] _225_;
  wire [30:0] _226_;
  wire [31:0] _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire [30:0] _231_;
  wire [31:0] _232_;
  wire _233_;
  wire [30:0] _234_;
  wire [30:0] _235_;
  wire [31:0] _236_;
  wire _237_;
  wire _238_;
  wire [30:0] _239_;
  wire [31:0] _240_;
  wire _241_;
  wire [30:0] _242_;
  wire [30:0] _243_;
  wire [30:0] _244_;
  wire [30:0] _245_;
  wire [31:0] _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire [30:0] _251_;
  wire [31:0] _252_;
  wire _253_;
  wire [30:0] _254_;
  wire [30:0] _255_;
  wire [31:0] _256_;
  wire _257_;
  wire _258_;
  wire [30:0] _259_;
  wire [31:0] _260_;
  wire _261_;
  wire [30:0] _262_;
  wire [30:0] _263_;
  wire [30:0] _264_;
  wire [31:0] _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire [30:0] _269_;
  wire [31:0] _270_;
  wire _271_;
  wire [30:0] _272_;
  wire [30:0] _273_;
  wire [31:0] _274_;
  wire _275_;
  wire _276_;
  wire [30:0] _277_;
  wire [31:0] _278_;
  wire _279_;
  wire [30:0] _280_;
  wire [30:0] _281_;
  wire [30:0] _282_;
  wire [30:0] _283_;
  wire [30:0] _284_;
  wire [30:0] _285_;
  wire [31:0] _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire [30:0] _293_;
  wire [31:0] _294_;
  wire _295_;
  wire [30:0] _296_;
  wire [30:0] _297_;
  wire [31:0] _298_;
  wire _299_;
  wire _300_;
  wire [30:0] _301_;
  wire [31:0] _302_;
  wire _303_;
  wire [30:0] _304_;
  wire [30:0] _305_;
  wire [30:0] _306_;
  wire [31:0] _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire [30:0] _311_;
  wire [31:0] _312_;
  wire _313_;
  wire [30:0] _314_;
  wire [30:0] _315_;
  wire [31:0] _316_;
  wire _317_;
  wire _318_;
  wire [30:0] _319_;
  wire [31:0] _320_;
  wire _321_;
  wire [30:0] _322_;
  wire [30:0] _323_;
  wire [30:0] _324_;
  wire [30:0] _325_;
  wire [31:0] _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire [30:0] _331_;
  wire [31:0] _332_;
  wire _333_;
  wire [30:0] _334_;
  wire [30:0] _335_;
  wire [31:0] _336_;
  wire _337_;
  wire _338_;
  wire [30:0] _339_;
  wire [31:0] _340_;
  wire _341_;
  wire [30:0] _342_;
  wire [30:0] _343_;
  wire [30:0] _344_;
  wire [31:0] _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire [30:0] _349_;
  wire [31:0] _350_;
  wire _351_;
  wire [30:0] _352_;
  wire [30:0] _353_;
  wire [31:0] _354_;
  wire _355_;
  wire _356_;
  wire [30:0] _357_;
  wire [31:0] _358_;
  wire _359_;
  wire [30:0] _360_;
  wire [30:0] _361_;
  wire [30:0] _362_;
  wire [30:0] _363_;
  wire [30:0] _364_;
  wire [31:0] _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire [30:0] _371_;
  wire [31:0] _372_;
  wire _373_;
  wire [30:0] _374_;
  wire [30:0] _375_;
  wire [31:0] _376_;
  wire _377_;
  wire _378_;
  wire [30:0] _379_;
  wire [31:0] _380_;
  wire _381_;
  wire [30:0] _382_;
  wire [30:0] _383_;
  wire [30:0] _384_;
  wire [31:0] _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire [30:0] _389_;
  wire [31:0] _390_;
  wire _391_;
  wire [30:0] _392_;
  wire [30:0] _393_;
  wire [31:0] _394_;
  wire _395_;
  wire _396_;
  wire [30:0] _397_;
  wire [31:0] _398_;
  wire _399_;
  wire [30:0] _400_;
  wire [30:0] _401_;
  wire [30:0] _402_;
  wire [30:0] _403_;
  wire [31:0] _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire [30:0] _409_;
  wire [31:0] _410_;
  wire _411_;
  wire [30:0] _412_;
  wire [30:0] _413_;
  wire [31:0] _414_;
  wire _415_;
  wire _416_;
  wire [30:0] _417_;
  wire [31:0] _418_;
  wire _419_;
  wire [30:0] _420_;
  wire [30:0] _421_;
  wire [30:0] _422_;
  wire [31:0] _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire [30:0] _427_;
  wire [31:0] _428_;
  wire _429_;
  wire [30:0] _430_;
  wire [30:0] _431_;
  wire [31:0] _432_;
  wire _433_;
  wire _434_;
  wire [30:0] _435_;
  wire [31:0] _436_;
  wire _437_;
  wire [30:0] _438_;
  wire [30:0] _439_;
  wire [30:0] _440_;
  wire [30:0] _441_;
  wire [30:0] _442_;
  wire [30:0] _443_;
  wire [30:0] _444_;
  wire _445_;
  wire [31:0] _446_;
  wire [15:0] _447_;
  wire _448_;
  wire [31:0] _449_;
  wire [15:0] _450_;
  wire _451_;
  reg [31:0] _452_;
  reg [15:0] _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire [31:0] _457_;
  wire [31:0] _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire _466_;
  wire _467_;
  input clk_i;
  output [31:0] coarse_o;
  reg [31:0] coarse_time;
  output [15:0] fine_o;
  input inp_i;
  reg pulse;
  input restart_i;
  input rst_n_i;
  input rst_time_n_i;
  reg [128:0] tap1;
  reg [128:0] tap2;
  reg trigger;
  output trigger_o;
  assign _153_ = _152_ ? 31'h00000001 : 31'h00000000;
  assign _154_ = 32'd2 + { 1'h0, _153_ };
  assign _155_ = tap2[117] == tap2[116];
  assign _156_ = _155_ ? 31'h00000001 : 31'h00000000;
  assign _157_ = _151_ ? _154_[30:0] : _156_;
  assign _158_ = 32'd4 + { 1'h0, _157_ };
  assign _159_ = tap2[114] == tap2[112];
  assign _160_ = tap2[115] == tap2[114];
  assign _161_ = _160_ ? 31'h00000001 : 31'h00000000;
  assign _162_ = 32'd2 + { 1'h0, _161_ };
  assign _163_ = tap2[113] == tap2[112];
  assign _164_ = _163_ ? 31'h00000001 : 31'h00000000;
  assign _165_ = _159_ ? _162_[30:0] : _164_;
  assign _166_ = _150_ ? _158_[30:0] : _165_;
  assign _167_ = _128_ ? _149_[30:0] : _166_;
  assign _168_ = 32'd16 + { 1'h0, _167_ };
  assign _169_ = tap2[104] == tap2[96];
  assign _170_ = tap2[108] == tap2[104];
  assign _171_ = tap2[110] == tap2[108];
  assign _172_ = tap2[111] == tap2[110];
  assign _173_ = _172_ ? 31'h00000001 : 31'h00000000;
  assign _174_ = 32'd2 + { 1'h0, _173_ };
  assign _175_ = tap2[109] == tap2[108];
  assign _176_ = _175_ ? 31'h00000001 : 31'h00000000;
  assign _177_ = _171_ ? _174_[30:0] : _176_;
  assign _178_ = 32'd4 + { 1'h0, _177_ };
  assign _179_ = tap2[106] == tap2[104];
  assign _180_ = tap2[107] == tap2[106];
  assign _181_ = _180_ ? 31'h00000001 : 31'h00000000;
  assign _182_ = 32'd2 + { 1'h0, _181_ };
  assign _183_ = tap2[105] == tap2[104];
  assign _184_ = _183_ ? 31'h00000001 : 31'h00000000;
  assign _185_ = _179_ ? _182_[30:0] : _184_;
  assign _186_ = _170_ ? _178_[30:0] : _185_;
  assign _187_ = 32'd8 + { 1'h0, _186_ };
  assign _188_ = tap2[100] == tap2[96];
  assign _189_ = tap2[102] == tap2[100];
  assign _190_ = tap2[103] == tap2[102];
  assign _191_ = _190_ ? 31'h00000001 : 31'h00000000;
  assign _192_ = 32'd2 + { 1'h0, _191_ };
  assign _193_ = tap2[101] == tap2[100];
  assign _194_ = _193_ ? 31'h00000001 : 31'h00000000;
  assign _195_ = _189_ ? _192_[30:0] : _194_;
  assign _196_ = 32'd4 + { 1'h0, _195_ };
  assign _197_ = tap2[98] == tap2[96];
  assign _198_ = tap2[99] == tap2[98];
  assign _199_ = _198_ ? 31'h00000001 : 31'h00000000;
  assign _200_ = 32'd2 + { 1'h0, _199_ };
  assign _201_ = tap2[97] == tap2[96];
  assign _202_ = _201_ ? 31'h00000001 : 31'h00000000;
  assign _203_ = _197_ ? _200_[30:0] : _202_;
  assign _204_ = _188_ ? _196_[30:0] : _203_;
  assign _205_ = _169_ ? _187_[30:0] : _204_;
  assign _206_ = _127_ ? _168_[30:0] : _205_;
  assign _207_ = 32'd32 + { 1'h0, _206_ };
  assign _208_ = tap2[80] == tap2[64];
  assign _209_ = tap2[88] == tap2[80];
  assign _210_ = tap2[92] == tap2[88];
  assign _211_ = tap2[94] == tap2[92];
  assign _212_ = tap2[95] == tap2[94];
  assign _213_ = _212_ ? 31'h00000001 : 31'h00000000;
  assign _214_ = 32'd2 + { 1'h0, _213_ };
  assign _215_ = tap2[93] == tap2[92];
  assign _216_ = _215_ ? 31'h00000001 : 31'h00000000;
  assign _217_ = _211_ ? _214_[30:0] : _216_;
  assign _218_ = 32'd4 + { 1'h0, _217_ };
  assign _219_ = tap2[90] == tap2[88];
  assign _220_ = tap2[91] == tap2[90];
  assign _221_ = _220_ ? 31'h00000001 : 31'h00000000;
  assign _222_ = 32'd2 + { 1'h0, _221_ };
  assign _223_ = tap2[89] == tap2[88];
  assign _224_ = _223_ ? 31'h00000001 : 31'h00000000;
  assign _225_ = _219_ ? _222_[30:0] : _224_;
  assign _226_ = _210_ ? _218_[30:0] : _225_;
  assign _227_ = 32'd8 + { 1'h0, _226_ };
  assign _228_ = tap2[84] == tap2[80];
  assign _229_ = tap2[86] == tap2[84];
  assign _230_ = tap2[87] == tap2[86];
  assign _231_ = _230_ ? 31'h00000001 : 31'h00000000;
  assign _232_ = 32'd2 + { 1'h0, _231_ };
  assign _233_ = tap2[85] == tap2[84];
  assign _234_ = _233_ ? 31'h00000001 : 31'h00000000;
  assign _235_ = _229_ ? _232_[30:0] : _234_;
  assign _236_ = 32'd4 + { 1'h0, _235_ };
  assign _237_ = tap2[82] == tap2[80];
  assign _238_ = tap2[83] == tap2[82];
  assign _239_ = _238_ ? 31'h00000001 : 31'h00000000;
  assign _240_ = 32'd2 + { 1'h0, _239_ };
  assign _241_ = tap2[81] == tap2[80];
  assign _242_ = _241_ ? 31'h00000001 : 31'h00000000;
  assign _243_ = _237_ ? _240_[30:0] : _242_;
  assign _244_ = _228_ ? _236_[30:0] : _243_;
  assign _245_ = _209_ ? _227_[30:0] : _244_;
  assign _246_ = 32'd16 + { 1'h0, _245_ };
  assign _247_ = tap2[72] == tap2[64];
  assign _248_ = tap2[76] == tap2[72];
  assign _249_ = tap2[78] == tap2[76];
  assign _250_ = tap2[79] == tap2[78];
  assign _251_ = _250_ ? 31'h00000001 : 31'h00000000;
  assign _252_ = 32'd2 + { 1'h0, _251_ };
  assign _253_ = tap2[77] == tap2[76];
  assign _254_ = _253_ ? 31'h00000001 : 31'h00000000;
  assign _255_ = _249_ ? _252_[30:0] : _254_;
  assign _256_ = 32'd4 + { 1'h0, _255_ };
  assign _257_ = tap2[74] == tap2[72];
  assign _258_ = tap2[75] == tap2[74];
  assign _259_ = _258_ ? 31'h00000001 : 31'h00000000;
  assign _260_ = 32'd2 + { 1'h0, _259_ };
  assign _261_ = tap2[73] == tap2[72];
  assign _262_ = _261_ ? 31'h00000001 : 31'h00000000;
  assign _263_ = _257_ ? _260_[30:0] : _262_;
  assign _264_ = _248_ ? _256_[30:0] : _263_;
  assign _265_ = 32'd8 + { 1'h0, _264_ };
  assign _266_ = tap2[68] == tap2[64];
  assign _267_ = tap2[70] == tap2[68];
  assign _268_ = tap2[71] == tap2[70];
  assign _269_ = _268_ ? 31'h00000001 : 31'h00000000;
  assign _270_ = 32'd2 + { 1'h0, _269_ };
  assign _271_ = tap2[69] == tap2[68];
  assign _272_ = _271_ ? 31'h00000001 : 31'h00000000;
  assign _273_ = _267_ ? _270_[30:0] : _272_;
  assign _274_ = 32'd4 + { 1'h0, _273_ };
  assign _275_ = tap2[66] == tap2[64];
  assign _276_ = tap2[67] == tap2[66];
  assign _277_ = _276_ ? 31'h00000001 : 31'h00000000;
  assign _278_ = 32'd2 + { 1'h0, _277_ };
  assign _279_ = tap2[65] == tap2[64];
  assign _280_ = _279_ ? 31'h00000001 : 31'h00000000;
  assign _281_ = _275_ ? _278_[30:0] : _280_;
  assign _282_ = _266_ ? _274_[30:0] : _281_;
  assign _283_ = _247_ ? _265_[30:0] : _282_;
  assign _284_ = _208_ ? _246_[30:0] : _283_;
  assign _285_ = _126_ ? _207_[30:0] : _284_;
  assign _286_ = 32'd64 + { 1'h0, _285_ };
  assign _287_ = tap2[32] == tap2[0];
  assign _288_ = tap2[48] == tap2[32];
  assign _454_ = ~ rst_time_n_i;
  assign _289_ = tap2[56] == tap2[48];
  assign _455_ = ~ rst_n_i;
  assign _290_ = tap2[60] == tap2[56];
  assign _456_ = _454_ | _455_;
  assign _291_ = tap2[62] == tap2[60];
  assign _292_ = tap2[63] == tap2[62];
  assign _457_ = coarse_time + 32'd1;
  assign _293_ = _292_ ? 31'h00000001 : 31'h00000000;
  assign _294_ = 32'd2 + { 1'h0, _293_ };
  assign _458_ = _456_ ? 32'd0 : _457_;
  assign _295_ = tap2[61] == tap2[60];
  assign _296_ = _295_ ? 31'h00000001 : 31'h00000000;
  assign _297_ = _291_ ? _294_[30:0] : _296_;
  assign _298_ = 32'd4 + { 1'h0, _297_ };
  always @(posedge clk_i)
      coarse_time <= _458_;
  assign _299_ = tap2[58] == tap2[56];
  assign _300_ = tap2[59] == tap2[58];
  assign _301_ = _300_ ? 31'h00000001 : 31'h00000000;
  assign _302_ = 32'd2 + { 1'h0, _301_ };
  assign _303_ = tap2[57] == tap2[56];
  assign _304_ = _303_ ? 31'h00000001 : 31'h00000000;
  assign _305_ = _299_ ? _302_[30:0] : _304_;
  assign _306_ = _290_ ? _298_[30:0] : _305_;
  assign _307_ = 32'd8 + { 1'h0, _306_ };
  always @(posedge clk_i)
      pulse <= tap2[0];
  assign _308_ = tap2[52] == tap2[48];
  assign _309_ = tap2[54] == tap2[52];
  assign _310_ = tap2[55] == tap2[54];
  assign _311_ = _310_ ? 31'h00000001 : 31'h00000000;
  assign _312_ = 32'd2 + { 1'h0, _311_ };
  assign _313_ = tap2[53] == tap2[52];
  assign _314_ = _313_ ? 31'h00000001 : 31'h00000000;
  assign _315_ = _309_ ? _312_[30:0] : _314_;
  assign _316_ = 32'd4 + { 1'h0, _315_ };
  assign _317_ = tap2[50] == tap2[48];
  assign _318_ = tap2[51] == tap2[50];
  assign _319_ = _318_ ? 31'h00000001 : 31'h00000000;
  assign _320_ = 32'd2 + { 1'h0, _319_ };
  assign _321_ = tap2[49] == tap2[48];
  assign _322_ = _321_ ? 31'h00000001 : 31'h00000000;
  assign _323_ = _317_ ? _320_[30:0] : _322_;
  assign _324_ = _308_ ? _316_[30:0] : _323_;
  assign _325_ = _289_ ? _307_[30:0] : _324_;
  assign _326_ = 32'd16 + { 1'h0, _325_ };
  assign _327_ = tap2[40] == tap2[32];
  assign _328_ = tap2[44] == tap2[40];
  assign _329_ = tap2[46] == tap2[44];
  assign _330_ = tap2[47] == tap2[46];
  assign _331_ = _330_ ? 31'h00000001 : 31'h00000000;
  assign _332_ = 32'd2 + { 1'h0, _331_ };
  assign _333_ = tap2[45] == tap2[44];
  assign _334_ = _333_ ? 31'h00000001 : 31'h00000000;
  assign _335_ = _329_ ? _332_[30:0] : _334_;
  assign _336_ = 32'd4 + { 1'h0, _335_ };
  assign _337_ = tap2[42] == tap2[40];
  assign _338_ = tap2[43] == tap2[42];
  assign _339_ = _338_ ? 31'h00000001 : 31'h00000000;
  assign _340_ = 32'd2 + { 1'h0, _339_ };
  assign _341_ = tap2[41] == tap2[40];
  assign _342_ = _341_ ? 31'h00000001 : 31'h00000000;
  assign _343_ = _337_ ? _340_[30:0] : _342_;
  assign _344_ = _328_ ? _336_[30:0] : _343_;
  assign _345_ = 32'd8 + { 1'h0, _344_ };
  assign _346_ = tap2[36] == tap2[32];
  assign _347_ = tap2[38] == tap2[36];
  assign _348_ = tap2[39] == tap2[38];
  assign _349_ = _348_ ? 31'h00000001 : 31'h00000000;
  assign _350_ = 32'd2 + { 1'h0, _349_ };
  assign _351_ = tap2[37] == tap2[36];
  assign _352_ = _351_ ? 31'h00000001 : 31'h00000000;
  assign _353_ = _347_ ? _350_[30:0] : _352_;
  assign _354_ = 32'd4 + { 1'h0, _353_ };
  assign _355_ = tap2[34] == tap2[32];
  assign _356_ = tap2[35] == tap2[34];
  assign _357_ = _356_ ? 31'h00000001 : 31'h00000000;
  assign _358_ = 32'd2 + { 1'h0, _357_ };
  assign _359_ = tap2[33] == tap2[32];
  assign _360_ = _359_ ? 31'h00000001 : 31'h00000000;
  assign _361_ = _355_ ? _358_[30:0] : _360_;
  assign _362_ = _346_ ? _354_[30:0] : _361_;
  assign _363_ = _327_ ? _345_[30:0] : _362_;
  assign _364_ = _288_ ? _326_[30:0] : _363_;
  assign _365_ = 32'd32 + { 1'h0, _364_ };
  assign _366_ = tap2[16] == tap2[0];
  assign _367_ = tap2[24] == tap2[16];
  assign _368_ = tap2[28] == tap2[24];
  assign _369_ = tap2[30] == tap2[28];
  assign _370_ = tap2[31] == tap2[30];
  assign _371_ = _370_ ? 31'h00000001 : 31'h00000000;
  assign _372_ = 32'd2 + { 1'h0, _371_ };
  assign _373_ = tap2[29] == tap2[28];
  assign _374_ = _373_ ? 31'h00000001 : 31'h00000000;
  assign _375_ = _369_ ? _372_[30:0] : _374_;
  assign _376_ = 32'd4 + { 1'h0, _375_ };
  assign _377_ = tap2[26] == tap2[24];
  assign _378_ = tap2[27] == tap2[26];
  assign _379_ = _378_ ? 31'h00000001 : 31'h00000000;
  assign _380_ = 32'd2 + { 1'h0, _379_ };
  assign _381_ = tap2[25] == tap2[24];
  assign _382_ = _381_ ? 31'h00000001 : 31'h00000000;
  assign _383_ = _377_ ? _380_[30:0] : _382_;
  assign _384_ = _368_ ? _376_[30:0] : _383_;
  assign _385_ = 32'd8 + { 1'h0, _384_ };
  assign _386_ = tap2[20] == tap2[16];
  assign _387_ = tap2[22] == tap2[20];
  assign _388_ = tap2[23] == tap2[22];
  assign _389_ = _388_ ? 31'h00000001 : 31'h00000000;
  assign _390_ = 32'd2 + { 1'h0, _389_ };
  assign _391_ = tap2[21] == tap2[20];
  assign _392_ = _391_ ? 31'h00000001 : 31'h00000000;
  assign _393_ = _387_ ? _390_[30:0] : _392_;
  assign _394_ = 32'd4 + { 1'h0, _393_ };
  assign _395_ = tap2[18] == tap2[16];
  assign _396_ = tap2[19] == tap2[18];
  assign _397_ = _396_ ? 31'h00000001 : 31'h00000000;
  assign _398_ = 32'd2 + { 1'h0, _397_ };
  assign _399_ = tap2[17] == tap2[16];
  assign _400_ = _399_ ? 31'h00000001 : 31'h00000000;
  assign _401_ = _395_ ? _398_[30:0] : _400_;
  assign _402_ = _386_ ? _394_[30:0] : _401_;
  assign _403_ = _367_ ? _385_[30:0] : _402_;
  assign _404_ = 32'd16 + { 1'h0, _403_ };
  assign _405_ = tap2[8] == tap2[0];
  assign _406_ = tap2[12] == tap2[8];
  assign _407_ = tap2[14] == tap2[12];
  assign _408_ = tap2[15] == tap2[14];
  assign _409_ = _408_ ? 31'h00000001 : 31'h00000000;
  assign _410_ = 32'd2 + { 1'h0, _409_ };
  assign _411_ = tap2[13] == tap2[12];
  assign _412_ = _411_ ? 31'h00000001 : 31'h00000000;
  assign _413_ = _407_ ? _410_[30:0] : _412_;
  assign _414_ = 32'd4 + { 1'h0, _413_ };
  assign _415_ = tap2[10] == tap2[8];
  assign _416_ = tap2[11] == tap2[10];
  assign _417_ = _416_ ? 31'h00000001 : 31'h00000000;
  assign _418_ = 32'd2 + { 1'h0, _417_ };
  assign _419_ = tap2[9] == tap2[8];
  assign _420_ = _419_ ? 31'h00000001 : 31'h00000000;
  assign _421_ = _415_ ? _418_[30:0] : _420_;
  assign _422_ = _406_ ? _414_[30:0] : _421_;
  assign _423_ = 32'd8 + { 1'h0, _422_ };
  assign _424_ = tap2[4] == tap2[0];
  assign _425_ = tap2[6] == tap2[4];
  assign _426_ = tap2[7] == tap2[6];
  assign _427_ = _426_ ? 31'h00000001 : 31'h00000000;
  assign _428_ = 32'd2 + { 1'h0, _427_ };
  assign _429_ = tap2[5] == tap2[4];
  assign _430_ = _429_ ? 31'h00000001 : 31'h00000000;
  assign _431_ = _425_ ? _428_[30:0] : _430_;
  assign _432_ = 32'd4 + { 1'h0, _431_ };
  assign _433_ = tap2[2] == tap2[0];
  assign _434_ = tap2[3] == tap2[2];
  assign _435_ = _434_ ? 31'h00000001 : 31'h00000000;
  assign _436_ = 32'd2 + { 1'h0, _435_ };
  assign _437_ = tap2[1] == tap2[0];
  assign _438_ = _437_ ? 31'h00000001 : 31'h00000000;
  assign _439_ = _433_ ? _436_[30:0] : _438_;
  assign _440_ = _424_ ? _432_[30:0] : _439_;
  assign _441_ = _405_ ? _423_[30:0] : _440_;
  assign _442_ = _366_ ? _404_[30:0] : _441_;
  assign _443_ = _287_ ? _365_[30:0] : _442_;
  assign _444_ = _125_ ? _286_[30:0] : _443_;
  assign _445_ = restart_i ? 1'h0 : trigger;
  assign _446_ = _123_ ? _124_ : _452_;
  assign _447_ = _123_ ? _444_[15:0] : _453_;
  assign _448_ = _123_ ? 1'h1 : _445_;
  assign _449_ = _119_ ? _452_ : _446_;
  assign _450_ = _119_ ? _453_ : _447_;
  assign _451_ = _119_ ? 1'h0 : _448_;
  always @(posedge clk_i)
      _452_ <= _449_;
  always @(posedge clk_i)
      _453_ <= _450_;
  always @(posedge clk_i)
      trigger <= _451_;
  always @(posedge clk_i)
      tap1 <= { _118_, _117_, _116_, _115_, _114_, _113_, _112_, _111_, _110_, _109_, _108_, _107_, _106_, _105_, _104_, _103_, _102_, _101_, _100_, _099_, _098_, _097_, _096_, _095_, _094_, _093_, _092_, _091_, _090_, _089_, _088_, _087_, _086_, _085_, _084_, _083_, _082_, _081_, _080_, _079_, _078_, _077_, _076_, _075_, _074_, _073_, _072_, _071_, _070_, _069_, _068_, _067_, _066_, _065_, _064_, _063_, _062_, _061_, _060_, _059_, _058_, _057_, _056_, _055_, _054_, _053_, _052_, _051_, _050_, _049_, _048_, _047_, _046_, _045_, _044_, _043_, _042_, _041_, _040_, _039_, _038_, _037_, _036_, _035_, _034_, _033_, _032_, _031_, _030_, _029_, _028_, _027_, _026_, _025_, _024_, _023_, _022_, _021_, _020_, _019_, _018_, _017_, _016_, _015_, _014_, _013_, _012_, _011_, _010_, _009_, _008_, _007_, _006_, _005_, _004_, _003_, _002_, _001_, _000_, _467_, _466_, _465_, _464_, _463_, _462_, _461_, _460_, _459_, inp_i };
  always @(posedge clk_i)
      tap2 <= tap1;
  assign _119_ = ~ rst_n_i;
  assign _120_ = pulse ^ tap2[0];
  assign _121_ = ~ trigger;
  assign _122_ = restart_i | _121_;
  assign _123_ = _120_ & _122_;
  assign _124_ = coarse_time - 32'd2;
  assign _125_ = tap2[64] == tap2[0];
  assign _126_ = tap2[96] == tap2[64];
  assign _127_ = tap2[112] == tap2[96];
  assign _128_ = tap2[120] == tap2[112];
  assign _129_ = tap2[124] == tap2[120];
  assign _130_ = tap2[126] == tap2[124];
  assign _131_ = tap2[127] == tap2[126];
  assign _132_ = tap2[128] == tap2[127];
  assign _133_ = _132_ ? 31'h00000001 : 31'h00000000;
  assign _134_ = 32'd1 + { 1'h0, _133_ };
  assign _135_ = _131_ ? _134_[30:0] : 31'h00000000;
  assign _136_ = 32'd2 + { 1'h0, _135_ };
  assign _137_ = tap2[125] == tap2[124];
  assign _138_ = _137_ ? 31'h00000001 : 31'h00000000;
  assign _139_ = _130_ ? _136_[30:0] : _138_;
  assign _140_ = 32'd4 + { 1'h0, _139_ };
  assign _141_ = tap2[122] == tap2[120];
  assign _142_ = tap2[123] == tap2[122];
  assign _143_ = _142_ ? 31'h00000001 : 31'h00000000;
  assign _144_ = 32'd2 + { 1'h0, _143_ };
  assign _145_ = tap2[121] == tap2[120];
  assign _146_ = _145_ ? 31'h00000001 : 31'h00000000;
  assign _147_ = _141_ ? _144_[30:0] : _146_;
  assign _148_ = _129_ ? _140_[30:0] : _147_;
  assign _149_ = 32'd8 + { 1'h0, _148_ };
  assign _150_ = tap2[116] == tap2[112];
  assign _151_ = tap2[118] == tap2[116];
  assign _152_ = tap2[119] == tap2[118];
  opentdc_delay \gen%0.inst  (
    .inp_i(inp_i),
    .out_o(_459_)
  );
  opentdc_delay \gen%1.inst  (
    .inp_i(_459_),
    .out_o(_460_)
  );
  opentdc_delay \gen%10.inst  (
    .inp_i(_000_),
    .out_o(_001_)
  );
  opentdc_delay \gen%100.inst  (
    .inp_i(_090_),
    .out_o(_091_)
  );
  opentdc_delay \gen%101.inst  (
    .inp_i(_091_),
    .out_o(_092_)
  );
  opentdc_delay \gen%102.inst  (
    .inp_i(_092_),
    .out_o(_093_)
  );
  opentdc_delay \gen%103.inst  (
    .inp_i(_093_),
    .out_o(_094_)
  );
  opentdc_delay \gen%104.inst  (
    .inp_i(_094_),
    .out_o(_095_)
  );
  opentdc_delay \gen%105.inst  (
    .inp_i(_095_),
    .out_o(_096_)
  );
  opentdc_delay \gen%106.inst  (
    .inp_i(_096_),
    .out_o(_097_)
  );
  opentdc_delay \gen%107.inst  (
    .inp_i(_097_),
    .out_o(_098_)
  );
  opentdc_delay \gen%108.inst  (
    .inp_i(_098_),
    .out_o(_099_)
  );
  opentdc_delay \gen%109.inst  (
    .inp_i(_099_),
    .out_o(_100_)
  );
  opentdc_delay \gen%11.inst  (
    .inp_i(_001_),
    .out_o(_002_)
  );
  opentdc_delay \gen%110.inst  (
    .inp_i(_100_),
    .out_o(_101_)
  );
  opentdc_delay \gen%111.inst  (
    .inp_i(_101_),
    .out_o(_102_)
  );
  opentdc_delay \gen%112.inst  (
    .inp_i(_102_),
    .out_o(_103_)
  );
  opentdc_delay \gen%113.inst  (
    .inp_i(_103_),
    .out_o(_104_)
  );
  opentdc_delay \gen%114.inst  (
    .inp_i(_104_),
    .out_o(_105_)
  );
  opentdc_delay \gen%115.inst  (
    .inp_i(_105_),
    .out_o(_106_)
  );
  opentdc_delay \gen%116.inst  (
    .inp_i(_106_),
    .out_o(_107_)
  );
  opentdc_delay \gen%117.inst  (
    .inp_i(_107_),
    .out_o(_108_)
  );
  opentdc_delay \gen%118.inst  (
    .inp_i(_108_),
    .out_o(_109_)
  );
  opentdc_delay \gen%119.inst  (
    .inp_i(_109_),
    .out_o(_110_)
  );
  opentdc_delay \gen%12.inst  (
    .inp_i(_002_),
    .out_o(_003_)
  );
  opentdc_delay \gen%120.inst  (
    .inp_i(_110_),
    .out_o(_111_)
  );
  opentdc_delay \gen%121.inst  (
    .inp_i(_111_),
    .out_o(_112_)
  );
  opentdc_delay \gen%122.inst  (
    .inp_i(_112_),
    .out_o(_113_)
  );
  opentdc_delay \gen%123.inst  (
    .inp_i(_113_),
    .out_o(_114_)
  );
  opentdc_delay \gen%124.inst  (
    .inp_i(_114_),
    .out_o(_115_)
  );
  opentdc_delay \gen%125.inst  (
    .inp_i(_115_),
    .out_o(_116_)
  );
  opentdc_delay \gen%126.inst  (
    .inp_i(_116_),
    .out_o(_117_)
  );
  opentdc_delay \gen%127.inst  (
    .inp_i(_117_),
    .out_o(_118_)
  );
  opentdc_delay \gen%13.inst  (
    .inp_i(_003_),
    .out_o(_004_)
  );
  opentdc_delay \gen%14.inst  (
    .inp_i(_004_),
    .out_o(_005_)
  );
  opentdc_delay \gen%15.inst  (
    .inp_i(_005_),
    .out_o(_006_)
  );
  opentdc_delay \gen%16.inst  (
    .inp_i(_006_),
    .out_o(_007_)
  );
  opentdc_delay \gen%17.inst  (
    .inp_i(_007_),
    .out_o(_008_)
  );
  opentdc_delay \gen%18.inst  (
    .inp_i(_008_),
    .out_o(_009_)
  );
  opentdc_delay \gen%19.inst  (
    .inp_i(_009_),
    .out_o(_010_)
  );
  opentdc_delay \gen%2.inst  (
    .inp_i(_460_),
    .out_o(_461_)
  );
  opentdc_delay \gen%20.inst  (
    .inp_i(_010_),
    .out_o(_011_)
  );
  opentdc_delay \gen%21.inst  (
    .inp_i(_011_),
    .out_o(_012_)
  );
  opentdc_delay \gen%22.inst  (
    .inp_i(_012_),
    .out_o(_013_)
  );
  opentdc_delay \gen%23.inst  (
    .inp_i(_013_),
    .out_o(_014_)
  );
  opentdc_delay \gen%24.inst  (
    .inp_i(_014_),
    .out_o(_015_)
  );
  opentdc_delay \gen%25.inst  (
    .inp_i(_015_),
    .out_o(_016_)
  );
  opentdc_delay \gen%26.inst  (
    .inp_i(_016_),
    .out_o(_017_)
  );
  opentdc_delay \gen%27.inst  (
    .inp_i(_017_),
    .out_o(_018_)
  );
  opentdc_delay \gen%28.inst  (
    .inp_i(_018_),
    .out_o(_019_)
  );
  opentdc_delay \gen%29.inst  (
    .inp_i(_019_),
    .out_o(_020_)
  );
  opentdc_delay \gen%3.inst  (
    .inp_i(_461_),
    .out_o(_462_)
  );
  opentdc_delay \gen%30.inst  (
    .inp_i(_020_),
    .out_o(_021_)
  );
  opentdc_delay \gen%31.inst  (
    .inp_i(_021_),
    .out_o(_022_)
  );
  opentdc_delay \gen%32.inst  (
    .inp_i(_022_),
    .out_o(_023_)
  );
  opentdc_delay \gen%33.inst  (
    .inp_i(_023_),
    .out_o(_024_)
  );
  opentdc_delay \gen%34.inst  (
    .inp_i(_024_),
    .out_o(_025_)
  );
  opentdc_delay \gen%35.inst  (
    .inp_i(_025_),
    .out_o(_026_)
  );
  opentdc_delay \gen%36.inst  (
    .inp_i(_026_),
    .out_o(_027_)
  );
  opentdc_delay \gen%37.inst  (
    .inp_i(_027_),
    .out_o(_028_)
  );
  opentdc_delay \gen%38.inst  (
    .inp_i(_028_),
    .out_o(_029_)
  );
  opentdc_delay \gen%39.inst  (
    .inp_i(_029_),
    .out_o(_030_)
  );
  opentdc_delay \gen%4.inst  (
    .inp_i(_462_),
    .out_o(_463_)
  );
  opentdc_delay \gen%40.inst  (
    .inp_i(_030_),
    .out_o(_031_)
  );
  opentdc_delay \gen%41.inst  (
    .inp_i(_031_),
    .out_o(_032_)
  );
  opentdc_delay \gen%42.inst  (
    .inp_i(_032_),
    .out_o(_033_)
  );
  opentdc_delay \gen%43.inst  (
    .inp_i(_033_),
    .out_o(_034_)
  );
  opentdc_delay \gen%44.inst  (
    .inp_i(_034_),
    .out_o(_035_)
  );
  opentdc_delay \gen%45.inst  (
    .inp_i(_035_),
    .out_o(_036_)
  );
  opentdc_delay \gen%46.inst  (
    .inp_i(_036_),
    .out_o(_037_)
  );
  opentdc_delay \gen%47.inst  (
    .inp_i(_037_),
    .out_o(_038_)
  );
  opentdc_delay \gen%48.inst  (
    .inp_i(_038_),
    .out_o(_039_)
  );
  opentdc_delay \gen%49.inst  (
    .inp_i(_039_),
    .out_o(_040_)
  );
  opentdc_delay \gen%5.inst  (
    .inp_i(_463_),
    .out_o(_464_)
  );
  opentdc_delay \gen%50.inst  (
    .inp_i(_040_),
    .out_o(_041_)
  );
  opentdc_delay \gen%51.inst  (
    .inp_i(_041_),
    .out_o(_042_)
  );
  opentdc_delay \gen%52.inst  (
    .inp_i(_042_),
    .out_o(_043_)
  );
  opentdc_delay \gen%53.inst  (
    .inp_i(_043_),
    .out_o(_044_)
  );
  opentdc_delay \gen%54.inst  (
    .inp_i(_044_),
    .out_o(_045_)
  );
  opentdc_delay \gen%55.inst  (
    .inp_i(_045_),
    .out_o(_046_)
  );
  opentdc_delay \gen%56.inst  (
    .inp_i(_046_),
    .out_o(_047_)
  );
  opentdc_delay \gen%57.inst  (
    .inp_i(_047_),
    .out_o(_048_)
  );
  opentdc_delay \gen%58.inst  (
    .inp_i(_048_),
    .out_o(_049_)
  );
  opentdc_delay \gen%59.inst  (
    .inp_i(_049_),
    .out_o(_050_)
  );
  opentdc_delay \gen%6.inst  (
    .inp_i(_464_),
    .out_o(_465_)
  );
  opentdc_delay \gen%60.inst  (
    .inp_i(_050_),
    .out_o(_051_)
  );
  opentdc_delay \gen%61.inst  (
    .inp_i(_051_),
    .out_o(_052_)
  );
  opentdc_delay \gen%62.inst  (
    .inp_i(_052_),
    .out_o(_053_)
  );
  opentdc_delay \gen%63.inst  (
    .inp_i(_053_),
    .out_o(_054_)
  );
  opentdc_delay \gen%64.inst  (
    .inp_i(_054_),
    .out_o(_055_)
  );
  opentdc_delay \gen%65.inst  (
    .inp_i(_055_),
    .out_o(_056_)
  );
  opentdc_delay \gen%66.inst  (
    .inp_i(_056_),
    .out_o(_057_)
  );
  opentdc_delay \gen%67.inst  (
    .inp_i(_057_),
    .out_o(_058_)
  );
  opentdc_delay \gen%68.inst  (
    .inp_i(_058_),
    .out_o(_059_)
  );
  opentdc_delay \gen%69.inst  (
    .inp_i(_059_),
    .out_o(_060_)
  );
  opentdc_delay \gen%7.inst  (
    .inp_i(_465_),
    .out_o(_466_)
  );
  opentdc_delay \gen%70.inst  (
    .inp_i(_060_),
    .out_o(_061_)
  );
  opentdc_delay \gen%71.inst  (
    .inp_i(_061_),
    .out_o(_062_)
  );
  opentdc_delay \gen%72.inst  (
    .inp_i(_062_),
    .out_o(_063_)
  );
  opentdc_delay \gen%73.inst  (
    .inp_i(_063_),
    .out_o(_064_)
  );
  opentdc_delay \gen%74.inst  (
    .inp_i(_064_),
    .out_o(_065_)
  );
  opentdc_delay \gen%75.inst  (
    .inp_i(_065_),
    .out_o(_066_)
  );
  opentdc_delay \gen%76.inst  (
    .inp_i(_066_),
    .out_o(_067_)
  );
  opentdc_delay \gen%77.inst  (
    .inp_i(_067_),
    .out_o(_068_)
  );
  opentdc_delay \gen%78.inst  (
    .inp_i(_068_),
    .out_o(_069_)
  );
  opentdc_delay \gen%79.inst  (
    .inp_i(_069_),
    .out_o(_070_)
  );
  opentdc_delay \gen%8.inst  (
    .inp_i(_466_),
    .out_o(_467_)
  );
  opentdc_delay \gen%80.inst  (
    .inp_i(_070_),
    .out_o(_071_)
  );
  opentdc_delay \gen%81.inst  (
    .inp_i(_071_),
    .out_o(_072_)
  );
  opentdc_delay \gen%82.inst  (
    .inp_i(_072_),
    .out_o(_073_)
  );
  opentdc_delay \gen%83.inst  (
    .inp_i(_073_),
    .out_o(_074_)
  );
  opentdc_delay \gen%84.inst  (
    .inp_i(_074_),
    .out_o(_075_)
  );
  opentdc_delay \gen%85.inst  (
    .inp_i(_075_),
    .out_o(_076_)
  );
  opentdc_delay \gen%86.inst  (
    .inp_i(_076_),
    .out_o(_077_)
  );
  opentdc_delay \gen%87.inst  (
    .inp_i(_077_),
    .out_o(_078_)
  );
  opentdc_delay \gen%88.inst  (
    .inp_i(_078_),
    .out_o(_079_)
  );
  opentdc_delay \gen%89.inst  (
    .inp_i(_079_),
    .out_o(_080_)
  );
  opentdc_delay \gen%9.inst  (
    .inp_i(_467_),
    .out_o(_000_)
  );
  opentdc_delay \gen%90.inst  (
    .inp_i(_080_),
    .out_o(_081_)
  );
  opentdc_delay \gen%91.inst  (
    .inp_i(_081_),
    .out_o(_082_)
  );
  opentdc_delay \gen%92.inst  (
    .inp_i(_082_),
    .out_o(_083_)
  );
  opentdc_delay \gen%93.inst  (
    .inp_i(_083_),
    .out_o(_084_)
  );
  opentdc_delay \gen%94.inst  (
    .inp_i(_084_),
    .out_o(_085_)
  );
  opentdc_delay \gen%95.inst  (
    .inp_i(_085_),
    .out_o(_086_)
  );
  opentdc_delay \gen%96.inst  (
    .inp_i(_086_),
    .out_o(_087_)
  );
  opentdc_delay \gen%97.inst  (
    .inp_i(_087_),
    .out_o(_088_)
  );
  opentdc_delay \gen%98.inst  (
    .inp_i(_088_),
    .out_o(_089_)
  );
  opentdc_delay \gen%99.inst  (
    .inp_i(_089_),
    .out_o(_090_)
  );
  assign trigger_o = trigger;
  assign coarse_o = _452_;
  assign fine_o = _453_;
endmodule

module opentdc_delay(inp_i, out_o);
  input inp_i;
  output out_o;
  assign out_o = inp_i;
endmodule
