/* Generated by Yosys 0.9+2406 (git sha1 f7fdd99, gcc 4.8.5 -fPIC -Os) */

module zero(n_o, s_o, w_o, e_o);
  output e_o;
  output n_o;
  output s_o;
  output w_o;
  assign n_o = 1'h0;
  assign s_o = 1'h0;
  assign w_o = 1'h0;
  assign e_o = 1'h0;
endmodule
